name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Publish to Cloudflare Workers
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      run: wrangler deploy