name: Deploy to Cloudflare Workers

on:
  workflow_call:
    inputs:
      CF_API_TOKEN:
        required: true
        type: string
        default: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID:
        required: true
        type: string
        default: ${{ secrets.CF_ACCOUNT_ID }}
      CF_ZONE_ID:
        required: true
        type: string
        default: ${{ secrets.CF_ZONE_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Publish to Cloudflare Workers
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.CF_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CF_ACCOUNT_ID }}
        CLOUDFLARE_ZONE_ID: ${{ inputs.CF_ZONE_ID }}
      run: wrangler deploy ./worker.js
