name: Deploy to GitHub Packages
on:
  workflow_call:
    inputs:
      workspace:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Publish to GitHub Packages
        run: mvn deploy --settings ${{ github.workspace }}/main/resources/settings.xml
