name: Deploy to Koyeb

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar jq
        run: sudo apt-get install jq

      - name: LogIn to Koyeb y almacenar token
        run: |
          BEARER_TOKEN=$(curl -X POST "https://app.koyeb.com/v1/account/login" \
          -H "Content-Type: application/json" \
          -d '{"email": "${{ secrets.KOYEB_EMAIL }}", "password": "${{ secrets.KOYEB_PASSWORD }}"}' \
          | jq -r '.token.id')
          echo "BEARER_TOKEN=$BEARER_TOKEN" >> $GITHUB_ENV
        
      - name: Trigger Koyeb Deployment
        run: |
          curl -X POST "https://app.koyeb.com/v1/services/${{ secrets.KOYEB_SERVICE_ID }}/redeploy" \
          -H "Authorization: Bearer ${{ env.BEARER_TOKEN }}"
