name: Deploy to Koyeb

on:
  workflow_call:
    inputs:
      project-app:
        type: string
        required: true
      project-name:
        type: string
        required: true
      project-id:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Koyeb CLI
        run: curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh

      - name: Create Koyeb Config File
        env:
          PATH: /home/runner/.koyeb/bin:$PATH
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          echo "token: ${KOYEB_API_TOKEN}" > ~/.koyeb.yaml

      - name: Deploy to Koyeb
        env:
          PATH: /home/runner/.koyeb/bin:$PATH
        run: |
          koyeb deploy . ${{ inputs.project-app }}/${{ inputs.project-name }} \
            --archive-builder docker
            --archive-docker-dockerfile ./Dockerfile
            --type WEB \
            --instance-type free \
            --ports ${{ secrets.SPRING_PORT }} \
            --env SPRING_PROFILE=${{ secrets.SPRING_PROFILE }} \
            --env SPRING_PORT=${{ secrets.SPRING_PORT }} \
            --env FOTG_MONGO_URI=${{ secrets.FOTG_MONGO_URI }} \
            --env GITHUB_USERNAME=${{ secrets.PACKAGE_USERNAME }} \
            --env GITHUB_TOKEN=${{ secrets.PACKAGE_TOKEN }}
