name: Deploy to Koyeb

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Trigger Koyeb Deployment
        run: |
          curl -X GET "${{ secrets.KOYEB_DEPLOY_URL }}"

        
