name: Deploy to Koyeb

on:
  workflow_call:
    inputs:
      url:
        description: 'URL to deploy services to Koyeb.'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Trigger Koyeb Deployment
        run: |
          curl -X GET "${{ inputs.url }}"

        
