name: Deploy to Koyeb

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        required: true
      project-id:
        type: string
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw
      
      - name: Build Spring Boot app
        run: ./mvnw package -DskipTests

      - name: Build Docker image
        run: docker build -t ${{ inputs.project-name }}:latest .

      - name: Save Docker image as tar file
        run: docker save ${{ inputs.project-name }}:latest -o ./${{ inputs.project-name }}.tar

      - name: Deploy to Koyeb
        run: |
          curl -X POST https://app.koyeb.com/v1/apps/${{ inputs.project-id }}/deployments \
            -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -F "file=@./${{ inputs.project-name }}.tar" \
            -F 'deploy={ "image": "docker.io/library/${{ inputs.project-name }}:latest" }'
